server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive_jwt

jwt:
  secretKey: mycustomsecret-thisisasecret-dontdivulgatehimplease-youremyconfident-donttalkaboutthissecret
  validityInMs: 3600000 # 1 hour
